[project]
name = "cnn-mle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "pytest>=9.0.2",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "ruff>=0.15.7",
]

[tool.ruff]
line-length = 100
target-version = "py310"
extend-include = ["*.ipynb"] # Ważne dla Twoich notatników!

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "NPY", "T20"]
ignore = ["D100", "D103"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]
