name: CI

# 1. KIEDY URUCHAMIAĆ?
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 2. POBIERZ KOD
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. ZAINSTALUJ UV
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      # 4. USTAW PYTHON
      - name: Set up Python
        run: uv python install

      # 5. INSTALACJA ZALEŻNOŚCI
      - name: Install dependencies
        run: uv sync --all-extras --dev

      # 6. SPRAWDZANIE JAKOŚCI (Ruff)
      - name: Run Ruff (Lint & Format)
        run: |
          uv run --prokect . ruff check .
          uv run --prokect . ruff format --check .

      # 7. TESTY (Pytest)
      - name: Run Tests
        run: uv run pytest